import { spawn } from 'node:child_process';
import { mkdirSync, readFileSync, renameSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { summarizeResearch, type ResearchAudit } from '../src/research/visibility-data';
import { runVisibilityBlock } from '../src/research/visibility';
import { RESEARCH_N, RESEARCH_VERSION, researchSeeds, visibilityConfig, visibilityPlanKey, VISIBILITY_CASES } from '../src/research/visibility-plan';
import { MODEL_VERSION } from '../src/sim/version';
import { researchSourceDigest } from './research-source';

const root = new URL('../', import.meta.url);
const sourceDigest = researchSourceDigest();
const planKey = visibilityPlanKey();
const cache = new URL(`test-results/research/${sourceDigest}/`, root);
mkdirSync(cache, { recursive: true });
const atomicWrite = (url: URL, body: string) => { const temp = new URL(`${url.href}.tmp`); writeFileSync(temp, body); renameSync(temp, url); };
const blocks = ([3, 0] as const).flatMap((door) => ([10, 20] as const).map((food) => ({ door, food, id: `${door}-${food}` })));
const blockId = process.argv.find((a) => a.startsWith('--block='))?.slice('--block='.length);

if (blockId) {
  const block = blocks.find((b) => b.id === blockId);
  if (!block) throw new Error('Unknown research block');
  const data = await runVisibilityBlock(block.door, block.food);
  if (researchSourceDigest() !== sourceDigest) throw new Error('Research source changed while running');
  atomicWrite(new URL(`${block.id}.json`, cache), JSON.stringify({ sourceDigest, planKey, ...data }));
} else {
  const check = process.argv.includes('--check');
  const fromAudit = process.argv.includes('--from-audit');
  if (check && fromAudit) throw new Error('--check requires a fresh run; omit --from-audit');
  const started = performance.now();
  let audit: ResearchAudit;
  if (fromAudit) {
    audit = JSON.parse(readFileSync(new URL('docs/studies/visibility-roles-v1-audit.json', root), 'utf8')) as ResearchAudit;
    if (audit.sourceDigest !== sourceDigest || audit.planKey !== planKey) throw new Error('Audit provenance is stale; run npm run research');
  } else {
    console.log(`${RESEARCH_VERSION}: 8 cells × 30 paired lunches × 2 reservation levels, 600 unique runs. Plan: docs/research-protocol.md`);
    const nWorkers = Number(process.env.CANTEEN_STUDY_WORKERS ?? 4);
    if (!Number.isInteger(nWorkers) || nWorkers < 1 || nWorkers > 4) throw new Error('CANTEEN_STUDY_WORKERS must be 1–4');
    let next = 0;
    await Promise.all(Array.from({ length: nWorkers }, async () => {
      while (next < blocks.length) {
        const block = blocks[next++];
        await new Promise<void>((resolve, reject) => {
          const child = spawn(process.execPath, [fileURLToPath(new URL('node_modules/vite-node/vite-node.mjs', root)), fileURLToPath(import.meta.url), `--block=${block.id}`], { stdio: ['ignore', 'ignore', 'inherit'] });
          child.on('error', reject);
          child.on('exit', (code) => code === 0 ? resolve() : reject(new Error(`Research block ${block.id}: exit ${code}`)));
        });
        console.log(`[${((performance.now() - started) / 1000).toFixed(0)} s] Finished door ${block.door}, food visibility ${block.food}`);
      }
    }));
    const data = blocks.map((b) => {
      const item = JSON.parse(readFileSync(new URL(`${b.id}.json`, cache), 'utf8')) as Awaited<ReturnType<typeof runVisibilityBlock>> & { sourceDigest: string; planKey: string };
      if (item.sourceDigest !== sourceDigest || item.planKey !== planKey) throw new Error('Invalid research checkpoint');
      return item;
    });
    audit = { version: RESEARCH_VERSION, model: MODEL_VERSION, sourceDigest, planKey, seeds: researchSeeds(), cases: VISIBILITY_CASES.map((c) => ({ ...c, config: visibilityConfig(c) })), runs: data.flatMap((d) => d.runs), pairs: data.flatMap((d) => d.pairs) };
  }
  if (researchSourceDigest() !== sourceDigest) throw new Error('Research source changed while running');
  const study = summarizeResearch(audit);
  if (study.n !== RESEARCH_N) throw new Error('Research sample incomplete');
  const tidy = (value: unknown) => JSON.stringify(value, (_key, v) => typeof v === 'number' && !Number.isInteger(v) ? Number(v.toPrecision(8)) : v);
  const format = (mean: number | null, lo: number | null, hi: number | null) => `${mean?.toFixed(2) ?? 'missing'} [${lo?.toFixed(3) ?? 'no interval'}, ${hi?.toFixed(3) ?? 'no interval'}]`;
  const row = (id: string) => study.rows.find((r) => r.id === id && r.fraction === 1)!;
  const gap = (id: string) => { const s = row(id).metrics.leftPct; return format(s.delta, s.lo, s.hi); };
  const broad = row('door3-claim20-food20');
  const report = [
    '# Visibility roles v1: when seeing farther changes reservation outcomes', '',
    `Separate research experiment on Model ${study.model}. Generated by \`npm run research\`. No real canteen pilot or empirical validation. [Protocol and predefined contrasts](../research-protocol.md).`, '',
    `${study.runs} complete runs, 8 factor combinations, ${study.n} fresh paired lunches per comparison at both 50% and 100% reservation. All 16 comparisons and 28 predefined contrasts are included. No missing or truncated runs. Seeds start from 100001 using batchSeeds; the original sensitivity block starts from 1.`, '',
    '## Reading the mechanism', '',
    `At 100% reservation with the seating check on, the leaving gap is ${gap('door3-claim10-food10')} pp with both ranges at 10 m; ${gap('door3-claim20-food10')} pp when only claimers see 20 m; ${gap('door3-claim10-food20')} pp when only food-searchers see 20 m; and ${gap('door3-claim20-food20')} pp with both at 20 m. Compare the role contrasts below to distinguish these mechanisms.`, '',
    `With both ranges at 20 m, the gap is ${gap('door0-claim20-food20')} pp when the seating check is off. With it on, the reservation change in door leaving is ${format(broad.metrics.doorLeftPct.delta, broad.metrics.doorLeftPct.lo, broad.metrics.doorLeftPct.hi)} pp and in queue leaving is ${format(broad.metrics.queueLeftPct.delta, broad.metrics.queueLeftPct.lo, broad.metrics.queueLeftPct.hi)} pp. Fewer queue departures can reflect fewer people entering.`, '',
    'Success and unavailable-seat diagnostics describe intermediate outcomes; they do not by themselves establish mediation. Role and door interventions identify effects within this simulator, conditional on all unchanged rules. Mean food-carrying times compare the people served in each canteen, who may differ. These measures cannot be collapsed into a policy winner without a stated value judgement.', '',
    '## Complete outcome grid', '',
    'All changes are reservation minus free flow, with pointwise 95% paired intervals. Lower leaving and plate time, and higher seat use and throughput, are preferable. Intervals describe simulated variation only and are unadjusted across comparisons. Door 3 = seating check on; door 0 = ignore seating. Distances are metres.', '',
    '| Door | Claim / food | Reserving | Leaving, pp | Plate time, s | Seat use, pp | Throughput, people/h |',
    '|---:|---|---:|---:|---:|---:|---:|',
    ...study.rows.map((r) => {
      const c = VISIBILITY_CASES.find((c) => c.id === r.id)!;
      return `| ${c.door} | ${c.claimer} / ${c.foodSearcher} | ${r.fraction * 100}% | ${(['leftPct', 'plateSeconds', 'seatUsePct', 'throughput'] as const).map((k) => format(r.metrics[k].delta, r.metrics[k].lo, r.metrics[k].hi)).join(' | ')} |`;
    }), '',
    '## Intermediate outcomes', '',
    'Counts and ratios are means across lunches. Success divides claimed groups by admitted reserving groups in each lunch. Unavailable empty seat-hours sum claimed-empty, held and blocked seat-time during the fixed arrival window. They are not peak occupancy or a measured real-world waste rate.', '',
    '| Door | Claim / food | Reserving | Admitted reserving groups | Successful claims | Success, % | Claim/fallback time, s | Unavailable empty seat-hours A / B | Door leaving change, pp | Queue leaving change, pp |',
    '|---:|---|---:|---:|---:|---:|---:|---:|---:|---:|',
    ...study.rows.map((r) => {
      const c = VISIBILITY_CASES.find((c) => c.id === r.id)!;
      const a = r.diagnostics.a, b = r.diagnostics.b;
      return `| ${c.door} | ${c.claimer} / ${c.foodSearcher} | ${r.fraction * 100}% | ${a.admittedReservingGroups.toFixed(1)} | ${a.claimedGroups.toFixed(1)} | ${a.claimSuccessPct?.toFixed(1)} | ${a.claimAttemptSeconds?.toFixed(1)} | ${a.unavailableEmptySeatHours.toFixed(1)} / ${b.unavailableEmptySeatHours.toFixed(1)} | ${format(r.metrics.doorLeftPct.delta, r.metrics.doorLeftPct.lo, r.metrics.doorLeftPct.hi)} | ${format(r.metrics.queueLeftPct.delta, r.metrics.queueLeftPct.lo, r.metrics.queueLeftPct.hi)} |`;
    }), '',
    '## All predefined contrasts', '',
    'Each entry is a change in the reservation effect, computed from per-seed differences of differences. Positive leaving means the intervention makes the reservation gap worse. Interaction is the claimer-range effect with 20 m food search minus that with 10 m. Door amplification is check-on minus check-off. Interval endpoints were not subtracted. Every contrast and its raw linear terms are in the compact JSON.', '',
    '| Contrast | Reserving | Leaving, pp | Plate time, s | Seat use, pp | Throughput, people/h |',
    '|---|---:|---:|---:|---:|---:|',
    ...study.contrasts.map((r) => `| ${r.label} | ${r.fraction * 100}% | ${(['leftPct', 'plateSeconds', 'seatUsePct', 'throughput'] as const).map((k) => format(r.metrics[k].mean, r.metrics[k].lo, r.metrics[k].hi)).join(' | ')} |`), '',
    '## Reproduce and audit', '',
    '- `src/research/visibility-plan.ts`: exact factors, default configuration and seed derivation.',
    '- `docs/studies/visibility-roles-v1-audit.json`: configuration per case, seeds, all run metrics and hashes, diagnostics, and exact paired outcome values.',
    '- `src/generated/research.json`: compact summaries, all contrasts and source/plan identity.',
    '- `npm run research -- --check`: fresh 600-run comparison with all published artifacts.',
    '- `npm run research -- --from-audit`: provenance-checked reconstruction only, for prose changes; not a fresh simulation.',
    '- Unit tests reconstruct every result, check all planned cells and verify that equal role ranges reproduce Model 2. The sanity suite reruns the first seed in every block with invariants enabled.', '',
    'The interactive animation and its estimates remain Model 2. The separate role variants cannot be loaded using Model 2 settings codes. A hash must be read with its model/experiment identity and settings.', '',
    `Experiment: \`${study.version}\`. Source SHA-256: \`${sourceDigest}\`.`, '',
  ].join('\n');
  const outputs: [string, string][] = [['src/generated/research.json', tidy(study) + '\n'], ['docs/studies/visibility-roles-v1-audit.json', JSON.stringify(audit) + '\n'], ['docs/studies/visibility-roles-v1.md', report]];
  for (const [path, body] of outputs) {
    if (check) { if (readFileSync(new URL(path, root), 'utf8') !== body) throw new Error(`Stale research artifact: ${path}`); }
    else atomicWrite(new URL(path, root), body);
  }
  console.log(`${check ? 'Verified fresh' : fromAudit ? 'Reconstructed from audit' : 'Generated fresh'} research artifacts in ${((performance.now() - started) / 1000).toFixed(1)} s.`);
}
